<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class CompleteUserSeeder extends Seeder
{
    public function run(): void
    {
        // Disable foreign key checks temporarily
        \DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        // Create all users from your data
        $users = [
            // Level 0 - Root users (no parent)
            [
                'id' => 1, 'parent_id' => null, 'hierarchy_level' => 0, 'designation_id' => 1, 'company_id' => null, 'department_id' => 1, 'branch_id' => null,
                'employee_id' => 'MAH-982328', 'firstname' => 'Mr. Sami', 'lastname' => 'Al Musalli', 'name' => 'Mr. Sami Al Musalli',
                'username' => 'sami_al_musalli', 'email' => 'sami.m@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => '2025-07-31 19:28:08', 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0112861721', 'mobile' => '0527054351', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 1,
                'created_at' => '2025-04-30 12:30:19', 'updated_at' => '2025-08-21 14:55:05',
            ],
            [
                'id' => 2, 'parent_id' => null, 'hierarchy_level' => null, 'designation_id' => null, 'company_id' => null, 'department_id' => null, 'branch_id' => null,
                'employee_id' => 'MAH-104318', 'firstname' => 'Department', 'lastname' => 'Director', 'name' => 'Managing Director',
                'username' => 'department_director', 'email' => 'director@example.com', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => '2025-09-04 18:53:17', 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0116773653', 'mobile' => '0526884279', 'gender' => null,
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 2,
                'created_at' => '2025-04-30 12:30:19', 'updated_at' => '2025-09-04 18:53:17',
            ],
            [
                'id' => 3, 'parent_id' => null, 'hierarchy_level' => null, 'designation_id' => null, 'company_id' => null, 'department_id' => null, 'branch_id' => null,
                'employee_id' => 'MAH-007916', 'firstname' => 'Team', 'lastname' => 'Manager', 'name' => 'Team Manager',
                'username' => 'team_manager', 'email' => 'manager@example.com', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => '2025-09-04 18:53:47', 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0116899869', 'mobile' => '0512781234', 'gender' => null,
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 3,
                'created_at' => '2025-04-30 12:30:20', 'updated_at' => '2025-09-04 18:53:47',
            ],
            [
                'id' => 4, 'parent_id' => null, 'hierarchy_level' => null, 'designation_id' => null, 'company_id' => null, 'department_id' => null, 'branch_id' => null,
                'employee_id' => 'MAH-749460', 'firstname' => 'Team', 'lastname' => 'Supervisor', 'name' => 'Team Supervisor',
                'username' => 'team_supervisor', 'email' => 'supervisor@example.com', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => '2025-09-04 18:54:09', 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0119423400', 'mobile' => '0591504254', 'gender' => null,
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 4,
                'created_at' => '2025-04-30 12:30:20', 'updated_at' => '2025-09-04 18:54:09',
            ],
            [
                'id' => 5, 'parent_id' => 1, 'hierarchy_level' => 1, 'designation_id' => 23, 'company_id' => null, 'department_id' => 2, 'branch_id' => null,
                'employee_id' => 'MAH-997238', 'firstname' => 'Mr.', 'lastname' => 'Melvin', 'name' => 'Mr.  Melvin',
                'username' => 'melvin', 'email' => 'melvin.nicolas@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => '2025-09-11 15:27:28', 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0117606521', 'mobile' => '0577331173', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 5,
                'created_at' => '2025-04-30 12:30:20', 'updated_at' => '2025-09-11 15:27:28',
            ],
            [
                'id' => 6, 'parent_id' => 1, 'hierarchy_level' => 1, 'designation_id' => 2, 'company_id' => null, 'department_id' => 3, 'branch_id' => null,
                'employee_id' => 'MAH-425452', 'firstname' => 'Muntaser', 'lastname' => 'Ali', 'name' => 'Muntaser Ali',
                'username' => 'muntaser_ali', 'email' => 'muntaser.ali@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => '2025-07-31 19:09:16', 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0118711522', 'mobile' => '0538586877', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 6,
                'created_at' => '2025-04-30 12:30:20', 'updated_at' => '2025-07-31 19:09:16',
            ],
            [
                'id' => 7, 'parent_id' => 1, 'hierarchy_level' => 1, 'designation_id' => 2, 'company_id' => null, 'department_id' => 4, 'branch_id' => null,
                'employee_id' => 'MAH-654199', 'firstname' => 'Sadeq', 'lastname' => 'Abdulkarim', 'name' => 'Sadeq Abdulkarim',
                'username' => 'sadeq_abdulkarim', 'email' => 'alsadeq.kona@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => '2025-07-31 20:34:49', 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0115136466', 'mobile' => '0574684120', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 7,
                'created_at' => '2025-04-30 12:30:21', 'updated_at' => '2025-07-31 20:34:49',
            ],
            [
                'id' => 8, 'parent_id' => 1, 'hierarchy_level' => 1, 'designation_id' => 2, 'company_id' => null, 'department_id' => 5, 'branch_id' => null,
                'employee_id' => 'MAH-806417', 'firstname' => 'Waheeb', 'lastname' => 'Hajjat', 'name' => 'Waheeb Hajjat',
                'username' => 'waheeb_hajjat', 'email' => 'waheeb.hajjat@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => '2025-09-10 17:41:03', 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0114181349', 'mobile' => '0587203171', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 8,
                'created_at' => '2025-04-30 12:30:21', 'updated_at' => '2025-09-10 17:41:03',
            ],
            [
                'id' => 9, 'parent_id' => 6, 'hierarchy_level' => 2, 'designation_id' => 4, 'company_id' => null, 'department_id' => 3, 'branch_id' => null,
                'employee_id' => 'MAH-116466', 'firstname' => 'Ibrahim', 'lastname' => 'Suliman', 'name' => 'Ibrahim  Suliman',
                'username' => 'ibrahim_suliman', 'email' => 'ibrahim.suliman@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => '2025-09-17 08:52:09', 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0113199068', 'mobile' => '0588806832', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 9,
                'created_at' => '2025-04-30 12:30:21', 'updated_at' => '2025-09-17 08:52:09',
            ],
            [
                'id' => 10, 'parent_id' => 6, 'hierarchy_level' => 2, 'designation_id' => 5, 'company_id' => null, 'department_id' => 3, 'branch_id' => null,
                'employee_id' => 'MAH-500080', 'firstname' => 'Fatima', 'lastname' => 'Alshari', 'name' => 'Fatima Alshari',
                'username' => 'fatima_alshari', 'email' => 'fatima_alshari@maharat.com', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => null, 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0118116370', 'mobile' => '0538320098', 'gender' => 'Female',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 1,
                'created_at' => '2025-04-30 12:30:21', 'updated_at' => '2025-05-13 17:11:40',
            ],
            [
                'id' => 11, 'parent_id' => 6, 'hierarchy_level' => 2, 'designation_id' => 6, 'company_id' => null, 'department_id' => 3, 'branch_id' => null,
                'employee_id' => 'MAH-110000', 'firstname' => 'Hottaf', 'lastname' => 'Hamed', 'name' => 'Hottaf  Hamed',
                'username' => 'hottaf_hamed', 'email' => 'hottaf.hassan@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => null, 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0111111111', 'mobile' => '0555555555', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 1,
                'created_at' => '2025-05-13 17:13:07', 'updated_at' => '2025-05-13 17:13:07',
            ],
            [
                'id' => 12, 'parent_id' => 7, 'hierarchy_level' => 2, 'designation_id' => 24, 'company_id' => null, 'department_id' => 4, 'branch_id' => null,
                'employee_id' => 'MAH-110001', 'firstname' => 'Hashim', 'lastname' => 'Alhassan', 'name' => 'Hashim Alhassan',
                'username' => 'hashim_alhassan', 'email' => 'hashim_alhassan@maharat.com', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => null, 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0111111111', 'mobile' => '0555555556', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 1,
                'created_at' => '2025-05-13 17:17:36', 'updated_at' => '2025-05-13 17:17:36',
            ],
            [
                'id' => 13, 'parent_id' => 7, 'hierarchy_level' => 2, 'designation_id' => 26, 'company_id' => null, 'department_id' => 4, 'branch_id' => null,
                'employee_id' => 'MAH-110003', 'firstname' => 'Abubaker', 'lastname' => 'Hashim', 'name' => 'Abubaker Hashim',
                'username' => 'abubaker_hashim', 'email' => 'abubaker.hashim@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => '2025-09-17 15:10:21', 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0111111111', 'mobile' => '0555555557', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 1,
                'created_at' => '2025-05-13 17:21:28', 'updated_at' => '2025-09-28 11:10:02',
            ],
            [
                'id' => 14, 'parent_id' => 13, 'hierarchy_level' => 3, 'designation_id' => 7, 'company_id' => null, 'department_id' => 4, 'branch_id' => null,
                'employee_id' => 'MAH-110004', 'firstname' => 'Hottaf', 'lastname' => 'hassan', 'name' => 'Hottaf  hassan',
                'username' => 'Hottaf hassan', 'email' => 'aiyd_almahan@maharat.com', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => null, 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0111111111', 'mobile' => '0555555559', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 1,
                'created_at' => '2025-05-13 17:25:54', 'updated_at' => '2025-08-21 14:51:53',
            ],
            [
                'id' => 15, 'parent_id' => 13, 'hierarchy_level' => 3, 'designation_id' => 8, 'company_id' => null, 'department_id' => 4, 'branch_id' => null,
                'employee_id' => 'MAH-110006', 'firstname' => 'Abdulaziz', 'lastname' => 'Ghalib', 'name' => 'Abdulaziz Ghalib',
                'username' => 'abdulaziz_ghalib', 'email' => 'abdulaziz.ghaleb@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => null, 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0111111111', 'mobile' => '0555555545', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 1,
                'created_at' => '2025-05-13 17:27:15', 'updated_at' => '2025-05-13 17:27:15',
            ],
            [
                'id' => 16, 'parent_id' => 13, 'hierarchy_level' => 3, 'designation_id' => 9, 'company_id' => null, 'department_id' => 4, 'branch_id' => null,
                'employee_id' => 'MAH-110007', 'firstname' => 'Mohammed', 'lastname' => 'Almulla', 'name' => 'Mohammed Almulla',
                'username' => 'mohammed_almulla', 'email' => 'mohammed_almulla@maharat.com', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => '2025-09-08 10:30:23', 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0111111111', 'mobile' => '0555555541', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 19,
                'created_at' => '2025-05-13 17:28:30', 'updated_at' => '2025-09-08 10:30:23',
            ],
            [
                'id' => 17, 'parent_id' => 13, 'hierarchy_level' => 3, 'designation_id' => 3, 'company_id' => null, 'department_id' => 4, 'branch_id' => null,
                'employee_id' => 'MAH-110008', 'firstname' => 'Abdullah', 'lastname' => 'Ghaleb', 'name' => 'Abdullah Ghaleb',
                'username' => 'abdullah_ghaleb', 'email' => 'abdullah.ghalib@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => '2025-08-14 13:02:24', 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0111111111', 'mobile' => '0555555542', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 20,
                'created_at' => '2025-05-13 17:29:42', 'updated_at' => '2025-09-25 14:22:43',
            ],
            [
                'id' => 18, 'parent_id' => 8, 'hierarchy_level' => 2, 'designation_id' => 23, 'company_id' => null, 'department_id' => 2, 'branch_id' => null,
                'employee_id' => 'MAH-110011', 'firstname' => 'Raja', 'lastname' => 'Raman', 'name' => 'Raja Raman',
                'username' => 'raja_raman', 'email' => 'rajadurai.raman@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => '2025-09-14 17:53:24', 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0111111111', 'mobile' => '0555555546', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 23,
                'created_at' => '2025-05-13 17:36:53', 'updated_at' => '2025-09-14 17:53:24',
            ],
            [
                'id' => 19, 'parent_id' => 8, 'hierarchy_level' => 2, 'designation_id' => 12, 'company_id' => null, 'department_id' => 5, 'branch_id' => null,
                'employee_id' => 'MAH-110012', 'firstname' => 'Abdullah', 'lastname' => 'Moheb', 'name' => 'Abdullah Moheb',
                'username' => 'abdullah_moheb', 'email' => 'abdallah.moheb@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => null, 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0113489574', 'mobile' => '0575676545', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 1,
                'created_at' => '2025-05-13 17:49:07', 'updated_at' => '2025-05-13 17:49:07',
            ],
            [
                'id' => 20, 'parent_id' => 8, 'hierarchy_level' => 2, 'designation_id' => 13, 'company_id' => null, 'department_id' => 5, 'branch_id' => null,
                'employee_id' => 'MAH-110013', 'firstname' => 'Mustafa', 'lastname' => 'Abdulakrim', 'name' => 'Mustafa Abdulakrim',
                'username' => 'mustafa_abdulakrim', 'email' => 'mustafa.abdelkarim@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => null, 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0116131489', 'mobile' => '0567876545', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 1,
                'created_at' => '2025-05-13 17:52:10', 'updated_at' => '2025-05-13 17:52:10',
            ],
            [
                'id' => 21, 'parent_id' => 8, 'hierarchy_level' => 2, 'designation_id' => 14, 'company_id' => null, 'department_id' => 5, 'branch_id' => null,
                'employee_id' => 'MAH-110014', 'firstname' => 'Ibrahim', 'lastname' => 'Abulenein', 'name' => 'Ibrahim Abulenein',
                'username' => 'ibrahim_abulenein', 'email' => 'ibrahim.abulenein@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => null, 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0116788767', 'mobile' => '0578765678', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 1,
                'created_at' => '2025-05-13 17:59:20', 'updated_at' => '2025-05-13 17:59:20',
            ],
            [
                'id' => 22, 'parent_id' => 8, 'hierarchy_level' => 2, 'designation_id' => 15, 'company_id' => null, 'department_id' => 5, 'branch_id' => null,
                'employee_id' => 'MAH-110015', 'firstname' => 'Hakeem', 'lastname' => 'Tayssir', 'name' => 'Hakeem Tayssir',
                'username' => 'hakeem_tayssir', 'email' => 'hakeem_tayssir@maharat.com', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => '2025-09-04 18:52:55', 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0119346776', 'mobile' => '0574567876', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 27,
                'created_at' => '2025-05-13 18:00:54', 'updated_at' => '2025-09-04 18:52:55',
            ],
            [
                'id' => 23, 'parent_id' => 8, 'hierarchy_level' => 2, 'designation_id' => 16, 'company_id' => null, 'department_id' => 5, 'branch_id' => null,
                'employee_id' => 'MAH-110016', 'firstname' => 'Awad', 'lastname' => 'Nasir', 'name' => 'Awad Nasir',
                'username' => 'awad_nasir', 'email' => 'awad.nasir@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => null, 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0118678764', 'mobile' => '0545676545', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 1,
                'created_at' => '2025-05-13 18:02:18', 'updated_at' => '2025-05-13 18:02:18',
            ],
            [
                'id' => 24, 'parent_id' => 8, 'hierarchy_level' => 2, 'designation_id' => 17, 'company_id' => null, 'department_id' => 5, 'branch_id' => null,
                'employee_id' => 'MAH-110017', 'firstname' => 'Abdullah', 'lastname' => 'Fadaan', 'name' => 'Abdullah Fadaan',
                'username' => 'abdullah_fadaan', 'email' => 'abdullah.fadaan@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => null, 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0114356765', 'mobile' => '0545665445', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 1,
                'created_at' => '2025-05-13 18:05:54', 'updated_at' => '2025-05-13 18:05:54',
            ],
            [
                'id' => 25, 'parent_id' => 19, 'hierarchy_level' => 3, 'designation_id' => 18, 'company_id' => null, 'department_id' => 5, 'branch_id' => null,
                'employee_id' => 'MAH-110018', 'firstname' => 'Ibrahim', 'lastname' => 'Hijazi', 'name' => 'Ibrahim Hijazi',
                'username' => 'ibrahim_hijazi', 'email' => 'ibrahim.hijazi@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => null, 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0115678765', 'mobile' => '0586567876', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 1,
                'created_at' => '2025-05-13 18:10:37', 'updated_at' => '2025-05-13 18:10:37',
            ],
            [
                'id' => 26, 'parent_id' => 20, 'hierarchy_level' => 3, 'designation_id' => 19, 'company_id' => null, 'department_id' => 5, 'branch_id' => null,
                'employee_id' => 'MAH-110019', 'firstname' => 'Yaseen', 'lastname' => 'Ibrahim', 'name' => 'Yaseen Ibrahim',
                'username' => 'yaseen_ibrahim', 'email' => 'yaseen.ebrahem@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => null, 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0116787655', 'mobile' => '0576545679', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 1,
                'created_at' => '2025-05-13 18:14:09', 'updated_at' => '2025-05-13 18:14:09',
            ],
            [
                'id' => 27, 'parent_id' => 22, 'hierarchy_level' => 3, 'designation_id' => 20, 'company_id' => null, 'department_id' => 5, 'branch_id' => null,
                'employee_id' => 'MAH-110020', 'firstname' => 'Reji', 'lastname' => 'Ramachandran', 'name' => 'Reji Ramachandran',
                'username' => 'reji_ramachandran', 'email' => 'reji.ramachandran@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => null, 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0118765678', 'mobile' => '0556789876', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 1,
                'created_at' => '2025-05-13 18:17:32', 'updated_at' => '2025-05-13 18:17:32',
            ],
            [
                'id' => 28, 'parent_id' => 22, 'hierarchy_level' => 3, 'designation_id' => 20, 'company_id' => null, 'department_id' => 5, 'branch_id' => null,
                'employee_id' => 'MAH-110021', 'firstname' => 'Jennis', 'lastname' => 'James', 'name' => 'Jennis James',
                'username' => 'jennis_james', 'email' => 'jennis.james@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => null, 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0117456786', 'mobile' => '0574567877', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 1,
                'created_at' => '2025-05-13 18:20:29', 'updated_at' => '2025-05-13 18:20:29',
            ],
            [
                'id' => 29, 'parent_id' => 22, 'hierarchy_level' => 3, 'designation_id' => 20, 'company_id' => null, 'department_id' => 5, 'branch_id' => null,
                'employee_id' => 'MAH-110022', 'firstname' => 'Nikil', 'lastname' => 'Sasidharan', 'name' => 'Nikil Sasidharan',
                'username' => 'nikil_sasidharan', 'email' => 'nikil.pillai@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => null, 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0113584567', 'mobile' => '0585434567', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 1,
                'created_at' => '2025-05-13 18:29:54', 'updated_at' => '2025-05-13 18:29:54',
            ],
            [
                'id' => 30, 'parent_id' => 22, 'hierarchy_level' => 3, 'designation_id' => 20, 'company_id' => null, 'department_id' => 5, 'branch_id' => null,
                'employee_id' => 'MAH-110023', 'firstname' => 'Biju', 'lastname' => 'Koshy', 'name' => 'Biju Koshy',
                'username' => 'biju_koshy', 'email' => 'biju.koshy@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => null, 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0117887654', 'mobile' => '0567898765', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 1,
                'created_at' => '2025-05-13 18:34:44', 'updated_at' => '2025-05-13 18:34:44',
            ],
            [
                'id' => 31, 'parent_id' => 7, 'hierarchy_level' => 2, 'designation_id' => 26, 'company_id' => null, 'department_id' => 4, 'branch_id' => null,
                'employee_id' => 'MAH-110002', 'firstname' => 'Abdulatif', 'lastname' => 'Osman', 'name' => 'Abdulatif  Osman',
                'username' => 'abdulatif_osman', 'email' => 'abdulatif.osman@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => '2025-09-17 15:10:21', 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0111111111', 'mobile' => '0555555557', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 1,
                'created_at' => '2025-05-13 17:21:28', 'updated_at' => '2025-09-17 15:10:21',
            ],
            [
                'id' => 32, 'parent_id' => 13, 'hierarchy_level' => 3, 'designation_id' => 10, 'company_id' => null, 'department_id' => 4, 'branch_id' => null,
                'employee_id' => 'MAH-110009', 'firstname' => 'Sheik', 'lastname' => 'Mohamed', 'name' => 'Sheik Mohamed',
                'username' => 'Sheik_Mohamed', 'email' => 'sheik.mohamed@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => '2025-09-17 15:21:15', 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0111111111', 'mobile' => '0555555543', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 1,
                'created_at' => '2025-05-13 17:30:49', 'updated_at' => '2025-09-25 03:56:08',
            ],
            [
                'id' => 33, 'parent_id' => 13, 'hierarchy_level' => 3, 'designation_id' => 11, 'company_id' => null, 'department_id' => 4, 'branch_id' => null,
                'employee_id' => 'MAH-110010', 'firstname' => 'Ali', 'lastname' => 'Saeed', 'name' => 'Ali Saeed',
                'username' => 'ali_saeed', 'email' => 'ali.saeed@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => '2025-08-05 15:04:20', 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0111111111', 'mobile' => '0555555544', 'gender' => 'Male',
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 22,
                'created_at' => '2025-05-13 17:32:45', 'updated_at' => '2025-08-05 15:04:20',
            ],
            [
                'id' => 34, 'parent_id' => 7, 'hierarchy_level' => 2, 'designation_id' => 23, 'company_id' => null, 'department_id' => 4, 'branch_id' => null,
                'employee_id' => 'MAH-110076', 'firstname' => 'Asik', 'lastname' => 'Ali', 'name' => 'Asik Ali',
                'username' => 'Asik.Ali', 'email' => 'asik.ali@maharat.edu.sa', 'password' => '$2y$12$mYKAkz4KxlTXQ2zjS.SqVeoKZF5JJMiD.e/Wt0vha8A6mknUKZ5py',
                'email_verified_at' => null, 'title' => null, 'description' => null, 'employee_type' => 'full-time',
                'language' => 'english', 'landline' => '0111111111', 'mobile' => '0558678666', 'gender' => null,
                'favourite_module' => null, 'enable_otp' => 0, 'is_salesman_linked' => null, 'login_id' => null,
                'api_token' => null, 'is_active' => 1, 'is_admin' => 0, 'last_login_at' => null, 'last_login_ip' => null,
                'profile_photo_path' => null, 'remember_token' => null, 'created_by' => null, 'updated_by' => 1,
                'created_at' => '2025-09-25 04:11:28', 'updated_at' => '2025-09-25 04:11:28',
            ],
        ];

        foreach ($users as $userData) {
            User::create($userData);
        }
        
        // Re-enable foreign key checks
        \DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        
        echo "All users created successfully!\n";
    }
}